---
apiVersion: apps/v1
kind: Deployment    
metadata:
  name: todomvc
  labels:
    app: todomvc
spec:
  replicas: 3
  minReadySeconds: 10
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: todomvc
  template:
    metadata:
      labels:
        app: todomvc
    spec:
      containers:
        - name: todomvc
          image: ghcr.io/alkaponees/todomvc:v1
          ports:
            - containerPort: 8080
          resources:
          limits:
            memory: "512Mi"
            cpu: "800m"
---