name: "CI-CD"

on: 
  push:
    # tags: ["v[0-9].[0-9]+.[0-9]+"]
    branches: [dev, stage, master]
  pull_request:
    branches: [dev, stage, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install NPM dependencies
        run: npm install
      - name: Build todomvc assests
        run: npm run build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          run: npm run cypress:run
          browser: chrome
      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GPR_USERNAME }}
      #     password: ${{ secrets.GPR_TOKEN}}
      # - name: Build and Push Image
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ghcr.io/${{secrets.GPR_USERNAME}}/todomvc:${{ github.sha }}

  deploy-dev:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: build
    if: github.repository_owner == 'alkaponees'
    environment: "Development"
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Semantic versioning
        id: vers-development
        uses: PaulHatch/semantic-version@v4.0.2
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          format: "v${major}.${minor}.${patch}-development${increment}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{secrets.GPR_USERNAME}}
          password: ${{secrets.GPR_PASSWORD}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and Push Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: docker.pkg.github.com/todomvc/container-test:${{ steps.vers-development.outputs.version }}



  # deploy-stage:
  #     name: Deploy to Staging
  #     runs-on: ubuntu-latest
  #     needs: [build,deploy-dev]
  #     environment: "Staging"
  #     if: github.repository_owner == 'alkaponees'
  #     permissions:
  #       id-token: write
  #       contents: read
  #     steps:
  #     - name: Semantic versioning
  #       id: vers-staging
  #       uses: PaulHatch/semantic-version@v4.0.2
  #       with:
  #         branch: main
  #         tag_prefix: "v"
  #         major_pattern: "BREAKING CHANGE:"
  #         minor_pattern: "feat:"
  #         format: "v${major}.${minor}.${patch}-staging${increment}"
  #     - name: Checkout
  #       uses: actions/checkout@v2
        
  #     - name: Setup Node
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 14
  #         registry-url: https://npm.pkg.github.com/
  #     # - name: Login to GitHub Container Registry
  #     #   uses: docker/login-action@v2
  #     #   with:
  #     #     registry: ghcr.io
  #     #     username: ${{secrets.GPR_USERNAME}}
  #     #     password: ${{secrets.GPR_PASSWORD}}
  #     # - name: Set up Docker Buildx
  #     #   uses: docker/setup-buildx-action@v2
  #     # - name: Build and Push Image
  #     #   uses: docker/build-push-action@v2
  #     #   with:
  #     #     context: .
  #     #     push: true
  #     #     tags: ghcr.io/alkaponees/container-test:${{ steps.vers-staging.outputs.version }}
